user_pref("layout.css.devPixelsPerPx", "-1");
user_pref("mousewheel.default.delta_multiplier_y", 80);
user_pref("widget.use-xdg-desktop-portal.file-picker", 1);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("browser.startup.homepage", "file:///home/akira/dotfiles/firefox/frontpage/index.html");
user_pref("widget.gtk.rounded-bottom-corners.enabled", true);
user_pref("sidebar.revamp", false);
user_pref("media.peerconnection.enabled", true);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.chrome.enabled", true);
user_pref("widget.use-xdg-desktop-portal.open-uri",2);
user_pref("full-screen-api.transition-duration.enter", 0 0);
user_pref("full-screen-api.transition-duration.leave", 0 0);
user_pref("ui.scrollToClick", 1);
