[opener]
play = [
    { run = 'mpv "$@"', orphan = true, for = "unix" },
]

edit = [
    { run = '$EDITOR "$@"', block = true, for = "unix" },
]

pic = [
    { run = 'gwenview "$@"', block = true, for = "unix" },
]

epub = [
    { run = 'foliate "$@"', block = true, for = "unix" },
]

open = [
    { run = 'xdg-open "$@"', desc = "Open" },
]

pdf = [
    { run = 'zathura "$@"', block = true, for = "unix" },
]

[open]
prepend_rules = [
    # JSON
    { mime = "application/json", use = "edit" },

    # EPUB
    { mime = "application/epub+zip", use = "epub" },

    # HTML
    { mime = "text/html", use = ["open", "edit"] },

    # Images
    { mime = "image/png",  use = "pic" },
    { mime = "image/jpeg", use = "pic" },

    # PDF
    { mime = "application/pdf", use = "pdf" },
]
