root=UUID=f71fa41d-24b8-42f4-a2c6-051933cd3b35 rootflags=subvol=@ rw
resume=UUID=b214c922-7060-4938-abc5-06a187a7e53b

loglevel=3
quiet
splash
vt.global_cursor_default=0

# drm.edid_firmware=HDMI-A-1:edid/edid.bin
# video=HDMI-A-1:1920x1080@60e
